### ISSUE TITLE
get_ionrec_rate returns NaNs for certain temperatures

### ISSUE THREAD

**Issue by jslavin** [AtomDB/pyatomdb#1]
For certain high temperatures get_ionrec_rate returns nan for the recombination rate.  To reproduce:
Z = 2
T = 10.**7.1
print get_ionrec_rate(T, False, Te_unit='K', Z=Z, z1=1)
(2.2826785794904936e-08, nan)

I haven't tried to track it down yet.  Of course at such a high temperature the recombination should be very small.  I suppose it could be an under or overflow issue, though I think that should throw an exception.

Jon

**Comment by jslavin** [comment]
Ah I see.  That was apparently a design choice for when extrap=False.  I'm not sure that was a good one, especially as the default.

**Comment by jagophile** [comment]
Not a smart choice. Needs to be fixed, yes.

**Comment by jagophile** [comment]
Default behaviour changed to extrappolation=True. Will be pushed out in v 0.0.3.1
