### ISSUE TITLE
Fail to get abundance data file

### ISSUE THREAD

**Issue by RichardYCJ** [AtomDB/pyatomdb#10]
I've got a problem to call the 'pyatomdb.spectrum.Session' function. The error info is given below:
```python
 python make_new_spec.py 
trying URL ftp://sao-ftp.harvard.edu/AtomDB/APED/misc/Abundances_v3.0.8a.fits.gz
Error trying to open file /home/richard_ycj/atomdb/APED/misc/Abundances_v3.0.8a.fits. Not found locally or on server.
Traceback (most recent call last):
  File "make_new_spec.py", line 7, in <module>
    data = pyatomdb.spectrum.Session()
  File "/usr/local/lib/python2.7/dist-packages/pyatomdb/spectrum.py", line 1610, in __init__
    self.set_abundset(abundset)
  File "/usr/local/lib/python2.7/dist-packages/pyatomdb/spectrum.py", line 2008, in set_abundset
    old = atomdb.get_abundance(abundset=self.default_abundset)
  File "/usr/local/lib/python2.7/dist-packages/pyatomdb/atomdb.py", line 979, in get_abundance
    ind = numpy.where(abunddata[1].data.field('Source')==abundset)[0]
TypeError: 'bool' object has no attribute '__getitem__'
```
 It says the 'Abundances_v3.0.8a.fits' is not available both on my PC or server. Then I go to the URL(ftp://sao-ftp.harvard.edu/AtomDB/APED/misc) and really fail to find the file. So is this problem occured because the file failed to download to my PC when initializing the pyatomdb or the file is just missing on server? Or it's a bug? 

PS: Sorry for the link. I fail to connect it to the ftp website so I just give it out.

**Comment by RichardYCJ** [comment]
One way to solve this problem is to just **replace** the missing file with 'Abundances_v2.0.0a.fits'.  
1. **Download** the file from the URL(*ftp://sao-ftp.harvard.edu/AtomDB/APED/misc*) 
2. **Unzip** the file to  *$ATOMDB/APED/misc* 
3. **Change** the  *$ATOMDB/filemap* file. Turn the abundances file name(*line 1*) into **Abundances_v2.0.0a.fits** 
Now the *'get_data'* or *'Session'* function will work. 

PS: My pyatomdb version is 3.0.9

**Comment by jagophile** [comment]
Hi RichardYCJ,

Apologies for this - the file did not copy to the server correctly for some reason. I have now put the file there.

It's not vastly different from the 2.0.0 file - it adds new abundance options, but for standard runs, doesn't change anything.

Let me know if this works for you.

Adam

**Comment by RichardYCJ** [comment]
The abundances file is now available and works well. I can get my spectrum! Thank you Mr. Foster @jagophile

**Comment by jagophile** [comment]
Your welcome. Closing.
