### ISSUE TITLE
Migration to Python3?

### ISSUE THREAD

**Issue by aximov** [AtomDB/pyatomdb#11]
Any plans?

**Comment by jagophile** [comment]
None yet. It's on the to do list, but it's a long list...

**Comment by eblur** [comment]
No promises, but I *might* try to tackle this at some point. It seems to mostly be string formatting and print statement errands.

**Comment by jagophile** [comment]
OK, There is a python 3 branch. It is still very much in testing... See the py3 branch to explore it.

**Comment by jagophile** [comment]
Python 3 branch seems stable ("py3"). This will be migrated to the main branch and released as version 1.0

**Comment by jagophile** [comment]
This is now the official default channel. Python 3 for everyone!
