### ISSUE TITLE
path issue in linear_approx*.so

### ISSUE THREAD

**Issue by facero** [AtomDB/pyatomdb#15]
Hi, thanks for this nice tool and the py3 effort !

I'm testing the py3 branch and have an issue at import. 
```
----> 1 import pyatomdb

~/Documents/Work/Program/pyatomdb/pyatomdb/pyatomdb/__init__.py in <module>()
     18   else:
     19     g = glob.glob("%s/../linear_approx*.so"%(PATH))
---> 20     liblinapprox_file = os.path.join(PATH,g[0])
```
My .so is located in a different directory :
`./build/lib.macosx-10.7-x86_64-3.6/linear_approx.cpython-36m-darwin.so`

If I replace the glob search by : 
` g = glob.glob("%s/../build/lib*/linear_approx*.so"%(PATH))` 
it works on my computer. Anyone else experiencing this issue ? 
Should this be fixed ?

**Comment by facero** [comment]
Ok I had to do `sudo python setup.py install` without the sudo the installation wasn't completed. Sorry

**Comment by jagophile** [comment]
Thanks for reporting this.

To confirm, you were installing the libraries to somewhere central on your computer but hadn't run as sudo, so the files weren't copied into the correct location? And once you fixed this, everything worked ok without having to modify any of the source?

**Comment by facero** [comment]
Yes, I did `python setup.py install`. This tried to copy files in my Anaconda directory but didn't suceed. When I import pyatomdb from the source dir the import wasn't working (because of the path issue).
When doing sudo this copied files in the Anaconda dir and the import was successful.
I will try to produce an example notebook with the py3 branch and report issues if I see any.
