### ISSUE TITLE
The cooling curve example no longer works

### ISSUE THREAD

**Issue by DavidT3** [AtomDB/pyatomdb#22]
The example you wrote for how to create a cooling curve makes use of spectrum.make_spectrum, which has been deprecated. As such the example fails, and is present in your master branch, the documentation PDF, and the read my docs. I've only just started exploring pyatomdb, but from what I understand so far the return_spectrum function of CIESession would be the right thing to go with here. 

Just thought you should know! If I write an equivalent example script I'll add it here to save you the trouble.

**Comment by jagophile** [comment]
Ah yes. Thank you for this. I am on vacation but will fix it on Monday.

**Comment by jagophile** [comment]
I have fixed this and extended the example in the Master branch. Please let me know if this works.
