### ISSUE TITLE
Add `pycurl` to the list of required packages in setup.py

### ISSUE THREAD

**Issue by eblur** [AtomDB/pyatomdb#25]
After a bunch of fiddling with setting up a conda environment so I can use the repo version of pyatomdb, I noticed that one of the packages you use was not included after I installed a clean Python 3.6 and 3.8 environment.

The package is pycurl (which you call in `import curl`). It can be installed via pip or conda package management systems. After installing it, I was able to run pyatomdb (version 0.10.3 and 0.10.5) as usual.

You might want to add it to the `install_requires` list in setup.py

**Comment by jagophile** [comment]
Thanks for this, and sorry it required so much fiddling. I've been through several iterations of this over the past few years, with wget, curl and pycurl all moving around and then working followed by not working. It's a weirdly moving goalpost for a simple "go fetch a file" library.

Anyway, I have added pycurl to setup.py, hopefully it now works without incident!

**Comment by jagophile** [comment]
Honestly, this whole thing is a mess. Pycurl does not install under pip (at least not on Linux) without errors, unless you manually massage it in there.

I think I will mark this as fixed, but I am going to have to add some documentation explaining how to install if pycurl won't.

**Comment by jagophile** [comment]
OK, fixes in v0.10.6 on pypi and github.
