### ISSUE TITLE
getting ionization out along with spectrum

### ISSUE THREAD

**Issue by jslavin** [AtomDB/pyatomdb#26]
Hi Adam et al.,

I have been looking at doing some NEI calculations with pyatomdb in which I want to get out the spectrum and the ionization. It looks to me that there is no way to do this from the current code in a single call. That is, you can get the spectrum by using the return_spectrum method of NEIsession, which internally calculates the NEI evolution of the ionization, but then there's no access to the calculated ionization. I can calculate the NEI evolution via calls to apec.return_ionbal, but it seems very inefficient to need to do that as well as the call to return_spectrum. I'm thinking that it'd be good to make the ionization an attribute of the NEIsession object. What do you think of that? I could implement it if you agree.

Jon

**Comment by jagophile** [comment]
Hi Jon, That's a good idea which also looks easy to implement. If you want to write it, then I'll happily pull it in, otherwise I'll add it to my list for the next release.

Cheers,
Adam

**Comment by jslavin** [comment]
Hi Adam,

I was able to implement it with two statements. Should I make a pull request? By the way, I don't see any straightforward way to do it for CIE, though that might also be useful.

Jon

**Comment by jagophile** [comment]
I finally pulled in your code, so I think this is now closed. Thanks for this!

Adam
