### ISSUE TITLE
A typo in apec.py routine

### ISSUE THREAD

**Issue by niu541412** [AtomDB/pyatomdb#29]
Hi, Adam
There is a typo in [apec.py](https://github.com/AtomDB/pyatomdb/blob/master/pyatomdb/pyatomdb/apec.py) routine.
In line 210 of apec.py:
                                    settings = settings, ***extra=extrap***)
should be 
***extrap=extrap***
This will cause an error when doing the slow calculation.

**Comment by jagophile** [comment]
Hi - thanks for this. I've fixed this now and pushed it out as version 0.10.7.

Cheers,
Adam
