### ISSUE TITLE
Install problem with pip

### ISSUE THREAD

**Issue by tekkamanmaverick** [AtomDB/pyatomdb#35]
Hi Adam,

I can't install pyatomdb in my computer with pip. The machine is mac os big sur. The error message as follow,

Collecting pyatomdb
  Using cached pyatomdb-0.10.8.tar.gz (19.4 MB)
Requirement already satisfied: requests in /usr/local/anaconda3/lib/python3.8/site-packages (from pyatomdb) (2.25.1)
Requirement already satisfied: wget in /usr/local/anaconda3/lib/python3.8/site-packages (from pyatomdb) (3.2)
Requirement already satisfied: numpy>=1.9.0 in /usr/local/anaconda3/lib/python3.8/site-packages (from pyatomdb) (1.20.3)
Requirement already satisfied: scipy>=1.4.0 in /usr/local/anaconda3/lib/python3.8/site-packages (from pyatomdb) (1.6.2)
Requirement already satisfied: joblib in /usr/local/anaconda3/lib/python3.8/site-packages (from pyatomdb) (1.0.1)
Requirement already satisfied: mock in /usr/local/anaconda3/lib/python3.8/site-packages (from pyatomdb) (4.0.3)
Requirement already satisfied: astropy in /usr/local/anaconda3/lib/python3.8/site-packages (from pyatomdb) (4.3.1)
Requirement already satisfied: pycurl in /usr/local/anaconda3/lib/python3.8/site-packages (from pyatomdb) (7.43.0.6)
Requirement already satisfied: pyerfa>=1.7.3 in /usr/local/anaconda3/lib/python3.8/site-packages (from astropy->pyatomdb) (2.0.0)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/anaconda3/lib/python3.8/site-packages (from requests->pyatomdb) (4.0.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/anaconda3/lib/python3.8/site-packages (from requests->pyatomdb) (1.26.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/anaconda3/lib/python3.8/site-packages (from requests->pyatomdb) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/anaconda3/lib/python3.8/site-packages (from requests->pyatomdb) (2.10)
Building wheels for collected packages: pyatomdb
  Building wheel for pyatomdb (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-6m7m1k6o/pyatomdb_31c98e2c8ada4a0ab7a801b7bcc4e66a/setup.py'"'"'; __file__='"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-6m7m1k6o/pyatomdb_31c98e2c8ada4a0ab7a801b7bcc4e66a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-wheel-0vwtpqmb
       cwd: /private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-6m7m1k6o/pyatomdb_31c98e2c8ada4a0ab7a801b7bcc4e66a/
  Complete output (27 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/atomdb.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/util.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/test_dep.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/spectrum.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/atomic.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/const.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/apec.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  creating build/lib.macosx-10.9-x86_64-3.8/tests
  copying tests/test1.py -> build/lib.macosx-10.9-x86_64-3.8/tests
  copying tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/tests
  running build_ext
  building 'linear_approx' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/usr/local/anaconda3=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /usr/local/anaconda3/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /usr/local/anaconda3/include -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -I/usr/local/anaconda3/include/python3.8 -c linear_approx.c -o build/temp.macosx-10.9-x86_64-3.8/linear_approx.o
  clang-10: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
  x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /usr/local/anaconda3/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /usr/local/anaconda3/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.8/linear_approx.o -o build/lib.macosx-10.9-x86_64-3.8/linear_approx.cpython-38-darwin.so
  ld: warning: -pie being ignored. It is only used when linking a main executable
  ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
  clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for pyatomdb
  Running setup.py clean for pyatomdb
Failed to build pyatomdb
Installing collected packages: pyatomdb
    Running setup.py install for pyatomdb ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-6m7m1k6o/pyatomdb_31c98e2c8ada4a0ab7a801b7bcc4e66a/setup.py'"'"'; __file__='"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-6m7m1k6o/pyatomdb_31c98e2c8ada4a0ab7a801b7bcc4e66a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-record-p3at37gj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/anaconda3/include/python3.8/pyatomdb
         cwd: /private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-6m7m1k6o/pyatomdb_31c98e2c8ada4a0ab7a801b7bcc4e66a/
    Complete output (27 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/atomdb.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/util.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/test_dep.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/spectrum.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/atomic.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/const.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/apec.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    creating build/lib.macosx-10.9-x86_64-3.8/tests
    copying tests/test1.py -> build/lib.macosx-10.9-x86_64-3.8/tests
    copying tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/tests
    running build_ext
    building 'linear_approx' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/usr/local/anaconda3=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /usr/local/anaconda3/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /usr/local/anaconda3/include -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -I/usr/local/anaconda3/include/python3.8 -c linear_approx.c -o build/temp.macosx-10.9-x86_64-3.8/linear_approx.o
    clang-10: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
    x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /usr/local/anaconda3/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /usr/local/anaconda3/include -arch x86_64 build/temp.macosx-10.9-x86_64-3.8/linear_approx.o -o build/lib.macosx-10.9-x86_64-3.8/linear_approx.cpython-38-darwin.so
    ld: warning: -pie being ignored. It is only used when linking a main executable
    ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
    clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-6m7m1k6o/pyatomdb_31c98e2c8ada4a0ab7a801b7bcc4e66a/setup.py'"'"'; __file__='"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-6m7m1k6o/pyatomdb_31c98e2c8ada4a0ab7a801b7bcc4e66a/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-record-p3at37gj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/anaconda3/include/python3.8/pyatomdb Check the logs for full command output.

Thank you and best wishes.

**Comment by jagophile** [comment]
I have now obtained access to a Big Sur mac. I will see if I can recreate the issue

**Comment by jagophile** [comment]
I haven't managed to recreate this issue. Have you managed to find a fix?

**Comment by tekkamanmaverick** [comment]
No. I still can't use it in macOS even I have updated my system.

**Comment by tekkamanmaverick** [comment]
The OS which I use now is 
`ProductName:	macOS`
`ProductVersion:	12.3`
`BuildVersion:	21E230`
The python I used is installed though anaconda which was built by brew,
`brew install --cask anaconda`
The version of conda is 
`conda 4.12.0`
The version of python is 
`Python 3.8.13`

I tried to install pyatomdb though
`pip install pyatomdb`

However, I get the error message as follow,
```
Building wheels for collected packages: pyatomdb
  Building wheel for pyatomdb (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-zp9mbi_t/pyatomdb_9dc4f24b2df54aeb87bc160d72b410ea/setup.py'"'"'; __file__='"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-zp9mbi_t/pyatomdb_9dc4f24b2df54aeb87bc160d72b410ea/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-wheel-pxria8my
       cwd: /private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-zp9mbi_t/pyatomdb_9dc4f24b2df54aeb87bc160d72b410ea/
  Complete output (27 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/atomdb.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/util.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/test_dep.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/spectrum.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/atomic.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/const.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  copying pyatomdb/apec.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
  creating build/lib.macosx-10.9-x86_64-3.8/tests
  copying tests/test1.py -> build/lib.macosx-10.9-x86_64-3.8/tests
  copying tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/tests
  running build_ext
  building 'linear_approx' extension
  creating build/temp.macosx-10.9-x86_64-3.8
  x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/usr/local/anaconda3=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /usr/local/anaconda3/include -D_FORTIFY_SOURCE=2 -isystem /usr/local/anaconda3/include -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -I/usr/local/anaconda3/include/python3.8 -c linear_approx.c -o build/temp.macosx-10.9-x86_64-3.8/linear_approx.o
  clang-12: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
  x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /usr/local/anaconda3/include -D_FORTIFY_SOURCE=2 -isystem /usr/local/anaconda3/include build/temp.macosx-10.9-x86_64-3.8/linear_approx.o -o build/lib.macosx-10.9-x86_64-3.8/linear_approx.cpython-38-darwin.so
  ld: warning: -pie being ignored. It is only used when linking a main executable
  ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
  clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command '/usr/local/anaconda3/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for pyatomdb
  Running setup.py clean for pyatomdb
Failed to build pyatomdb
Installing collected packages: pyatomdb
    Running setup.py install for pyatomdb ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/local/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-zp9mbi_t/pyatomdb_9dc4f24b2df54aeb87bc160d72b410ea/setup.py'"'"'; __file__='"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-zp9mbi_t/pyatomdb_9dc4f24b2df54aeb87bc160d72b410ea/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-record-lvt8__25/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/anaconda3/include/python3.8/pyatomdb
         cwd: /private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-zp9mbi_t/pyatomdb_9dc4f24b2df54aeb87bc160d72b410ea/
    Complete output (29 lines):
    running install
    /usr/local/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-x86_64-3.8
    creating build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/atomdb.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/util.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/test_dep.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/spectrum.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/atomic.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/const.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    copying pyatomdb/apec.py -> build/lib.macosx-10.9-x86_64-3.8/pyatomdb
    creating build/lib.macosx-10.9-x86_64-3.8/tests
    copying tests/test1.py -> build/lib.macosx-10.9-x86_64-3.8/tests
    copying tests/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/tests
    running build_ext
    building 'linear_approx' extension
    creating build/temp.macosx-10.9-x86_64-3.8
    x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/usr/local/anaconda3=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /usr/local/anaconda3/include -D_FORTIFY_SOURCE=2 -isystem /usr/local/anaconda3/include -DMAJOR_VERSION=1 -DMINOR_VERSION=0 -I/usr/local/anaconda3/include/python3.8 -c linear_approx.c -o build/temp.macosx-10.9-x86_64-3.8/linear_approx.o
    clang-12: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
    x86_64-apple-darwin13.4.0-clang -bundle -undefined dynamic_lookup -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -flto -Wl,-export_dynamic -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -Wl,-pie -Wl,-headerpad_max_install_names -Wl,-dead_strip_dylibs -Wl,-rpath,/usr/local/anaconda3/lib -L/usr/local/anaconda3/lib -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /usr/local/anaconda3/include -D_FORTIFY_SOURCE=2 -isystem /usr/local/anaconda3/include build/temp.macosx-10.9-x86_64-3.8/linear_approx.o -o build/lib.macosx-10.9-x86_64-3.8/linear_approx.cpython-38-darwin.so
    ld: warning: -pie being ignored. It is only used when linking a main executable
    ld: unsupported tapi file type '!tapi-tbd' in YAML file '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd' for architecture x86_64
    clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
    error: command '/usr/local/anaconda3/bin/x86_64-apple-darwin13.4.0-clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/anaconda3/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-zp9mbi_t/pyatomdb_9dc4f24b2df54aeb87bc160d72b410ea/setup.py'"'"'; __file__='"'"'/private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-install-zp9mbi_t/pyatomdb_9dc4f24b2df54aeb87bc160d72b410ea/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/bd/ckdfb6wn07l9g3yk4b3j37tc0000gn/T/pip-record-lvt8__25/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/anaconda3/include/python3.8/pyatomdb Check the logs for full command output.
```
