### ISSUE TITLE
"Will not thermally broaden lines" vebosity

### ISSUE THREAD

**Issue by ivvv** [AtomDB/pyatomdb#39]
When using `pyatomdb` with some other tools, like `threeML`, I see a number of messages on stdout, like this:

```
Will not thermally broaden lines
Will not thermally broaden lines
Will not thermally broaden lines
```

I guess these come from multiple calls to `spectrum.py` in `set_broadening()` method. Is it possible to have those only if the call to set_broadening requires verbosity?

**Comment by jagophile** [comment]
Hi ivvv,

I've fixed this now in the Master branch, and released version 0.10.9 on PyPI too. I'm not sure where threeML gets pyatomdb from, so it might pick this up.

As of now, the session class has a verbose variable. Currently it's False by default, and won't print to screen. I have to still do a thorough check for other print statements, etc, but it should solve your immediate problem.
