### ISSUE TITLE
Issue using high resolution rmf files with NEI sessions

### ISSUE THREAD

**Issue by courtt** [AtomDB/pyatomdb#42]
Hi Adam,

I'm having trouble with using rmf files of higher resolution. When I print the number of ebins directly from the rmf file there are ~7900 bins for a XRISM rmf. However, after running the following commands:
```
nei = spec.NEISession()
nei.set_response('XIS_BI.rmf', arf='XRT_BI_entireFOV.arf')
print(len(nei.ebins_out))
```
I get 4096 ebins. This causes a discrepancy when trying to calculate the spectra using return_spectrum():
`lum_ej = ne*nH*ab[jmax]*nei.return_spectrum(Te,1e11,init_pop=popul,freeze_ion_pop=True,teunit='K')*vol #ph/s/bin`
I am getting the following error
`ValueError: operands could not be broadcast together with shapes (7899,) (4096,)`
It appears that there is some error within the return_spectrum or setting of the rmf file. We are trying to parallelize this calculation across layers so that could have a part in it, however these seem to be the major causes of the hiccup

Thanks,
Travis Court

**Comment by jagophile** [comment]
HI Travis,

Thanks for this. Can you send me (afoster@cfa.harvard.edu)  the response files (XIS_BI.rmf & XRT_BI_entireFOV.arf) you are using so I can check it out? I keep finding subtle differences in the formats and it's possible (probable) that I'm mishandling this one.

Cheers,
Adam

**Comment by jagophile** [comment]
Hi, any follow up on the email I sent? Otherwise I will consider this closed.
