### ISSUE TITLE
Continuum seems not properly being calculated in pyatomdb.spectrum.make_spectrum

### ISSUE THREAD

**Issue by astrodoo** [AtomDB/pyatomdb#5]
I tried to calculate the spectrum at given temperature including all lines and continuum.
But the results looked not correct, and I checked that somehow the continuum was not added in the routine. 

I took a look at the spectrum.py and found that in make_spectrum function, it called make_ion_index_continuum function to add the continuum. The context was

cspectrum += make_ion_index_continuum(ebins, Z, cocofile=ccdat,\
                                           binunits=binunits, no_coco=-docont,\
                                           no_pseudo=-dopseudo)*abund[iZ] 

As I understood, if I set docont as True, the "no_coco" should be False. But, I think -True is not False in python context. So I changed -docont & -dopseudo into not(docont) & not(dopseudo), and then the results looks fine now. 

Best,
Doosoo

**Comment by jagophile** [comment]
Thank you - fixed this. Fix released in v0.0.3.1
