### ISSUE TITLE
"ilo = fchan[j]" should be "ilo = fchan[j] - 1", " ihi = fchan[j] + nchan[j]" should be " ihi = fchan[j] + nchan[j] - 1"

### ISSUE THREAD

**Issue by liuguanfu1120** [AtomDB/pyatomdb#50]
Hi, I would like to say that "ilo = fchan[j]" in [spectrum](https://github.com/AtomDB/pyatomdb/blob/master/pyatomdb/pyatomdb/spectrum.py) (line 2199 and 2244) should be "ilo = fchan[j] - 1" and 
"ihi = fchan[j] + nchan[j]" in [spectrum](https://github.com/AtomDB/pyatomdb/blob/master/pyatomdb/pyatomdb/spectrum.py) (line 2202 and 2247) should be "ihi = fchan[j] + nchan[j] - 1"

The rmf file from LEM could be downloaded at [LEM](https://github.com/liuguanfu1120/tmp/blob/main/lem_2ev_110422.rmf) (I downloaded it from LEM's official website and uploaded it to a temporary repository of mine.)

When using the rmf file from LEM like
```python
import pyatomdb
sess = pyatomdb.spectrum.CIESession()
sess.set_response(rmf ='lem_2ev_110422.rmf')
```
there is an error
```python
ValueError: could not broadcast input array from shape (213,) into shape (212,)
```

I located the problem, that is:
In [spectrum](https://github.com/AtomDB/pyatomdb/blob/master/pyatomdb/pyatomdb/spectrum.py), the original code is
```python
self.rmfmatrix = numpy.zeros([len(self.rmf[matrixname].data),len(self.rmf['EBOUNDS'].data)])
for ibin, i in enumerate(self.rmf[matrixname].data):

  lobound = 0

  fchan = i['F_CHAN']*1
  nchan = i['N_CHAN']*1

  if numpy.isscalar(fchan):
    fchan = numpy.array([fchan])
  fchan -= chanoffset
  if numpy.isscalar(nchan):
    nchan = numpy.array([nchan])

  for j in range(len(fchan)):
    ilo = fchan[j]
    if ilo < 0: continue

    ihi = fchan[j] + nchan[j]
    self.rmfmatrix[ibin,ilo:ihi]=i['MATRIX'][lobound:lobound+nchan[j]]
    lobound = lobound+nchan[j]
```
However, `ilo` (==`fchan[j]`), `ihi`, and `nchan[j]`  could be 11788, 12001, and 213.
The shape of `self.rmfmatrix` is (12000, 12000).
The shape of `self.rmfmatrix[ibin,ilo:ihi]` (`self.rmfmatrix[ibin, 11788:12001]`) is (212,), while that of `i['MATRIX'][lobound:lobound+nchan[j]]` (i['MATRIX'][lobound:lobound+213]) is (213,).

I think the bug originates that `fchan[j]` (the first channel whose matrix element is non-zero) starts from `1`, but the index of 
`self.rmfmatrix` starts from `0`.

**Comment by jagophile** [comment]
Hi,

This is an odd one because I think it's actually an issue with the rmf file which isn't picked up by other software. It indexes the energy bins from zero when defining them, but from 1 when defining the response matrix ( so "F_CHAN" in the "SPECRSP MATRIX" HDU starts from 1, but "CHANNEL" in the "EBOUNDS" HDU starts from 0).

I will put in code to handle this while throwing out a warning, but it is (I think!) technically an issue with the rmf as generated.

**Comment by liuguanfu1120** [comment]
Thanks a lot!
I would like to check it and try to contact one of the members of [LEM](https://www.lem-observatory.org/) for more details.

**Comment by jagophile** [comment]
I have pushed this to the main branch as version 0.11.5. Please test and let me know how it goes!

**Comment by jagophile** [comment]
OK, I have spoken the LEM team, and they have fixed it in the newest version of their files. I'm going to close the bug now.

**Comment by liuguanfu1120** [comment]
Many thanks!
