### ISSUE TITLE
example code to reproduces apec_coco tables 

### ISSUE THREAD

**Issue by renecotyfanboy** [AtomDB/pyatomdb#51]
Hi everyone, 
I was wondering if there is any pure pyAtomdb code to generate the tables released and used in XSPEC somewhere ? I want to experiment with other binning scheme and would require to recompute it from the ground 
Sincerely, 
Simon

**Comment by jagophile** [comment]
Can I ask what exactly you are planning on doing? Just so I can get an idea of what you are looking for.  We certainly do have that code, although the compression part is hardcoded. I could see about unlinking that if I know what you want to do.

Feel free to email me: afoster@cfa.harvard.edu and we can talk details.

**Comment by renecotyfanboy** [comment]
Hi, thank you for your answer! I'll continue the discussion by mail
