### ISSUE TITLE
bug with array lengths?

### ISSUE THREAD

**Issue by eblur** [AtomDB/pyatomdb#7]
Hi Adam,  I'm trying the new make spectrum tutorial from [readthedocs](http://atomdb.readthedocs.io/en/master/examples.html#make-a-spectrum-version-2-0) and I am getting an error with array lengths.  Is this a bug?

_Screenshots:_

![pyatomdb_err0](https://cloud.githubusercontent.com/assets/2516513/26357389/6b689c06-3fcf-11e7-9bbf-9df453ccff89.png)

![pyatomdb_err1](https://cloud.githubusercontent.com/assets/2516513/26357394/6fee0086-3fcf-11e7-808c-4c915e6b04c3.png)

**Comment by jagophile** [comment]
Good question. Looking into it now.

**Comment by jagophile** [comment]
As it turns out, Astro-H labels energy bins from 0, Chandra from 1. I had written the code for Astro-H. Adding an indexing-dependent offset fixes this.

Currently going through some tests, but bug should be closed soon with a new version in a few minutes.

**Comment by jagophile** [comment]
OK, bug fix complete. Up to date version in master branch on github, and version 0.0.3.4 packaged and ready for pypi.
